---
title: "Post hoc inference for two-sample tests"
author: "P. Neuvial and M. Perrot-Dockès"
date: "`r Sys.Date()`"
output: 
  html_document: default
  rmarkdown::html_vignette: default
  pdf_document: default
vignette: >
  %\VignetteIndexEntry{Post hoc inference for two-sample tests}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r load-data}
library("sansSouci")
my_url <- url("https://plmbox.math.cnrs.fr/f/755496cc4c154a6dbab0/?dl=1")
my_con <- gzcon(my_url)
dat <- readRDS(my_con)
close(my_con)
m <- nrow(dat)  ## number of genes
```

Perform $\lambda$-calibration:

```{r calibration}
alpha  <- 0.1
cal <- calibrateJER(X = dat, B = 100, alpha = alpha)
```

```{r Simes}
sk <- SimesThresholdFamily(m)
```


```{r calculate-bound}
## Order genes by decreasing test statistic
o <- order(cal$stat, decreasing = TRUE)
n_genes <- 400
genes <- 1:n_genes
FP <- cbind(lambda = curveMaxFP(cal$stat[o[genes]], cal$thr),
           Simes = curveMaxFP(cal$stat[o[genes]], sk(alpha)))
```

```{r plot-setup}
cols <- c("orange", "blue")
ltys <- c(1, 2)
labs <- c(expression(lambda-calibration), "Simes")
mar <- c(4, 5, 0, 0) + 0.1
```



```{r, FP}
par(mar = mar)
matplot(genes, FP, t = 'l', 
        xlab = "Number of selected genes",
        ylab = "Upper bound on the \nnumber of false discoveries",
        col = cols, 
        lty = ltys)
abline(a = 0, b = 1, lty = 3)
legend("bottomright", labs, col = cols, lty = ltys)
```

```{r, FDP}
par(mar = mar)
FDP <- FP/genes
matplot(genes, FDP, t = 'l', 
        xlab = "Number of selected genes",
        ylab = "Upper bound on the \nproportion of false discoveries",
        col = cols, 
        lty = ltys)
legend("bottomright", labs, col = cols, lty = ltys)
```

```{r, TP}
TP <- genes - FP
matplot(genes, TP, t = 'l', 
        xlab = "Number of selected genes",
        ylab = "Lower bound on the \nnumber of true discoveries",
        col = cols, 
        lty = ltys)
legend("bottomright", labs, col = cols, lty = ltys)
```

## Remarks

Note that the thresholds after $\lambda$-calibration correspond to the Simes thresholds with parameter $\lambda$:

```{r}
identical(cal$thr, sk(cal$lambda))
```


## Session information

```{r}
sessionInfo()
```

