// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// colSort
arma::mat colSort(arma::mat X);
RcppExport SEXP _sanssouci_colSort(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(colSort(X));
    return rcpp_result_gen;
END_RCPP
}
// partialColSortDescCpp
arma::mat partialColSortDescCpp(arma::mat X, int k);
RcppExport SEXP _sanssouci_partialColSortDescCpp(SEXP XSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(partialColSortDescCpp(X, k));
    return rcpp_result_gen;
END_RCPP
}
// partialColSortCpp
arma::mat partialColSortCpp(arma::mat X, int k);
RcppExport SEXP _sanssouci_partialColSortCpp(SEXP XSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(partialColSortCpp(X, k));
    return rcpp_result_gen;
END_RCPP
}
// posthocBySimes0Rcpp
double posthocBySimes0Rcpp(NumericVector p, NumericVector select, double alpha);
RcppExport SEXP _sanssouci_posthocBySimes0Rcpp(SEXP pSEXP, SEXP selectSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type select(selectSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(posthocBySimes0Rcpp(p, select, alpha));
    return rcpp_result_gen;
END_RCPP
}
// testBySignFlipping
arma::mat testBySignFlipping(arma::mat X, double B);
RcppExport SEXP _sanssouci_testBySignFlipping(SEXP XSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(testBySignFlipping(X, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sanssouci_colSort", (DL_FUNC) &_sanssouci_colSort, 1},
    {"_sanssouci_partialColSortDescCpp", (DL_FUNC) &_sanssouci_partialColSortDescCpp, 2},
    {"_sanssouci_partialColSortCpp", (DL_FUNC) &_sanssouci_partialColSortCpp, 2},
    {"_sanssouci_posthocBySimes0Rcpp", (DL_FUNC) &_sanssouci_posthocBySimes0Rcpp, 3},
    {"_sanssouci_testBySignFlipping", (DL_FUNC) &_sanssouci_testBySignFlipping, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_sanssouci(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
