# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colSort <- function(X) {
    .Call('_sansSouci_colSort', PACKAGE = 'sansSouci', X)
}

marginalKFWER <- function(thr, Z) {
    .Call('_sansSouci_marginalKFWER', PACKAGE = 'sansSouci', thr, Z)
}

partialColSortDescCpp <- function(X, k) {
    .Call('_sansSouci_partialColSortDescCpp', PACKAGE = 'sansSouci', X, k)
}

partialColSortCpp <- function(X, k) {
    .Call('_sansSouci_partialColSortCpp', PACKAGE = 'sansSouci', X, k)
}

#' @describeIn posthocBySimes Rcpp version
#' @export
posthocBySimes0Rcpp <- function(p, select, alpha) {
    .Call('_sansSouci_posthocBySimes0Rcpp', PACKAGE = 'sansSouci', p, select, alpha)
}

rowSortDesc <- function(X) {
    .Call('_sansSouci_rowSortDesc', PACKAGE = 'sansSouci', X)
}

testBySignFlipping <- function(X, B) {
    .Call('_sansSouci_testBySignFlipping', PACKAGE = 'sansSouci', X, B)
}

