# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

partialColSortDescCpp <- function(X, k) {
    .Call('_sanssouci_partialColSortDescCpp', PACKAGE = 'sanssouci', X, k)
}

partialColSortCpp <- function(X, k) {
    .Call('_sanssouci_partialColSortCpp', PACKAGE = 'sanssouci', X, k)
}

